apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: load-balancer-go-kubernetes
  name: go-kubernetes
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-go-kubernetes
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer-go-kubernetes
    spec:
      containers:
      - image: go-kubernetes:latest
        name: go-kubernetes
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"